### ISSUE TITLE
size of data stored

### ISSUE THREAD

**Issue by narayananl23** [transistorsoft/nativescript-background-geolocation-lt#57]
Since it is general questions .. I am skipping the environment stuff.

What is the size of locations.  When I pasted [http://bytesizematters.com/](url) it is approx. 900B, Without whitespace - 345b. 

10 sec interval, 6 per min, 360 per hour, 8640 per day is  7mb of storage (for 900b size).   
Based on the general experience of the tool. Does it even matter ?

In the future.. can I configure to reduce the size ?

For e.g. if I am only interested in  
odometer = "1643.2";
timestamp = "2017-02-17T13:13:02.072Z";
Cords.longitude
Cords.lattitude
 

              ```
  {
                activity =         {
                    confidence = 100;
                    type = unknown;
                };
                battery =         {
                    "is_charging" = 0;
                    level = "-1";
                };
                coords =         {
                    accuracy = 5;
                    altitude = 0;
                    altitudeAccuracy = "-1";
                    heading = "321.33";
                    latitude = "37.41535131";
                    longitude = "-122.21013769";
                    speed = "34.26";
                };
                "is_heartbeat" = 0;
                "is_moving" = 1;
                odometer = "1643.2";
                timestamp = "2017-02-17T13:13:02.072Z";
                uuid = "0E90DA79-6900-415D-A006-552911C11BF6";
            }
```

**Comment by christocracy** [comment]
Funny you should ask.  I just released new HTTP JSON Request Template feature yesterday to Cordova.  I'll be testing it with NS soon over the next few days.

Here's the preliminary doc:

# HTTP Features

## JSON Request Templates

The plugin supports customizable JSON request schemas with the following config options:

| Option             | Type       | Default     | Description |
|--------------------|------------|-------------|-------------|
|`httpRootProperty`  | `String`   | `location`  | The root key in the JSON to render records |
|`locationTemplate`  | `String`   | `undefined` | Optional template to render `location` data |
|`geofenceTemplate`  | `String`   | `undefined` | Optional template to render `geofence` data |

### `httpRootProperty`

Traditionally, the plugin had a hard-coded "Location Data Schema", where it automatically appended location-data to the `location` key in the JSON data, eg:

```javascript
bgGeo.configure({
  url: 'http://my_url',
  params: {
    myParams: {foo: 'bar'}
  }
});
```

```javascript
POST /my_url
{
  "location": {  // <-- hardcoded "httpRootProperty"
    "coords": {
        "latitude": 23.23232323,
        "longitude": 37.37373737
    }
  },
  "myParams": {
    "foo": "bar"
  }
}
```

With `httpRootProperty`, you can now customize this key:

```javascript
bgGeo.configure({
  url: 'http://my_url',
  httpRootProperty: 'data',
  params: {
    myParams: {foo: 'bar'}
  }
});
```

```javascript
POST /my_url
{
  "data": {  // <-- customizable "httpRootProperty"!
    "coords": {
        "latitude": 23.23232323,
        "longitude": 37.37373737
    }
  },
  "myParams": {
    "foo": "bar"
  }
}
```

#### `httpRootProperty: "."`

If you'd rather POST your data *as* the root of the JSON, use **`httpRootProperty: "."`**:

```javascript
bgGeo.configure({
  url: 'http://my_url',
  httpRootProperty: '.',
  params: {
    myParams: {foo: 'bar'}
  }
})
```

```javascript
POST /my_url
{
  "coords": {  // <-- location data place *as* the root of the JSON
      "latitude": 23.23232323,
      "longitude": 37.37373737
  },
  "myParams": {
    "foo": "bar"
  }
}
```

### `locationTemplate` & `geofenceTemplate`

If you wish to provide your own custom HTTP JSON schema, you can configure distinct templates for both `location` and `geofence` data.

```javascript
bgGeo.configure({
  url: 'http://my_url',
  httpRootProperty: 'data',
  params: {
    myParams: {foo: 'bar'}
  },
  locationTemplate: '{ "lat":{{latitude}}, "lng":{{longitude}} }',
  extras: {
    "location_extra_foo": "extra location data"
  }
})
```

```javascript
POST /my_url
{
  "data": {
    "lat": 45.5192657,
    "lng": -73.6169116,
    "location_extra_foo": "extra location data"
  },
  "myParams": {
    "foo": "bar"
  }
}
```

#### Quoting String Values

You're completely responsible for `"quoting"` your own `String` values.  The following will generate a JSON parsing error:

```javascript
bgGeo.configure({
  locationTemplate: '{ "event":{{event}} }',
});
```

In the logs, you'll find:
```
‼️-[TSLocation templateError:template:] locationTemplate error: Invalid value around character 10.
{ "event":{{event}} }
```

To fix this, the `String` tag `{{event}}` must be wrapped in `""`:

```javascript
bgGeo.configure({
  locationTemplate: '{ "event":"{{event}}" }',
});
```

#### Boolean, Float and Integer Values

`Boolean`, `Float` and `Integer` values do **not** require quoting:

```
bgGeo.configure({
  locationTemplate: '{ "is_moving":{{is_moving}}, "odometer":{{odometer}} }',
});
```

#### Array Templates

You're not forced to define your templates as an **`{Object}`** -- You can define them as an **`[Array]`** too.

```javascript
bgGeo.configure({
  url: 'http://my_url',
  httpRootProperty: 'data',
  params: {
    myParams: {foo: 'bar'}
  },
  locationTemplate: '[ {{latitude}}, {{longitude}} ]',
  extras: {
    "location_extra_foo": "extra location data"
  }
})
```

```javascript
POST /my_url
{
  "data": [
    45.5192657,
    -73.6169116,
    {"location_extra_foo": "extra location data"}  // <-- appended #extras
  ],
  "myParams": {
    "foo": "bar"
  }
}
```

:exclamation: `#extras` are automatically appened to the last element of the array as an `{Object}`.

#### Array Template with `httpRootProperty: "."`

:exclamation: This case is tricky and should probably be avoided, particularly if you have configured `#params`, since there no place in the request JSON to append them.

```javascript
bgGeo.configure({
  url: 'http://my_url',
  httpRootProperty: '.',
  params: {
    myParams: {foo: 'bar'}
  },
  locationTemplate: '[ {{latitude}}, {{longitude}} ]',
  extras: {
    "location_extra_foo": "extra location data"
  }
})
```

```javascript
- POST /my_url
 [  // <-- #params are lost.  There's no place in the data-structure to append them.
  45.5192657,
  -73.6169116,
  {
    "location_extra_foo": "extra location data"
  }
]
```

### Template Tags

#### Common Tags

The following template tags are common to both **`locationTemplate`** and **`geofenceTemplate`**:

| Tag | Type | Description |
|-----|------|-------------|
| `{{latitude}}` | `Float` ||
| `{{longitude}}` | `Float` ||
| `{{speed}}` | `Float` | Meters|
| `{{heading}}` | `Float` | Degress|
| `{{accuracy}}` | `Float` | Meters|
| `{{altitude}}` | `Float` | Meters|
| `{{altitude_accuracy}}` | `Float` | Meters|
| `{{timestamp}}` | `String` |ISO-8601|
| `{{uuid}}` | `String` |Unique ID|
| `{{event}}` | `String` |`motionchange|geofenee|heartbeat`
| `{{odometer}}` | `Float` | Meters|
| `{{activity_type}}` | `String` | `still|on_foot|running|on_bicycle|in_vehicle|unknown`|
| `{{activity_confidence}}` | `Integer` | 0-100%|
| `{{battery_level}}` | `Float` | 0-100%|
| `{{battery_is_charging}}` | `Boolean` | Is device plugged in?|

#### Geofence Tags

The following template tags are specific to **`geofenceTemplate`** only:

| Tag | Type | Description |
|-----|------|-------------|
| `{{geofence_identifier}}` | `String` | Which geofence?|
| `{{geofence_action}}` | `String` | `ENTER|EXIT`|

**Comment by narayananl23** [comment]
Awesome, I am glad to use this plugin... 

It was hard to start due to lack of knowledge of plugin, native script, google play requirements, understating of typescript and javascript relations, what IDE to use, started on windows env.. but once in these are the best set of tools. I used native script because of this plugin... I went reverse  :) and that may be the reason for my hard time.

**Comment by christocracy** [comment]
This functionality is now available in the branch [`templates`](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/templates).  The template features are **very** new a little tested.

See [HTTP Features](https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/templates/docs/http.md) for reference.
