### ISSUE TITLE
Conflict with NativeScript push notification plugin

### ISSUE THREAD

**Issue by loadchief** [transistorsoft/nativescript-background-geolocation-lt#70]
I am experiencing a conflict issue with the Google Services library used in this plugin. Errors are thrown in the Android build process when I try to use the NativeScript push notification plugin alongside yours.  After doing some research, I found that the problem is probably related to the following line:

https://github.com/transistorsoft/nativescript-background-geolocation-lt/blob/master/platforms/android/include.gradle#L12

Using a wildcard '+' character should not be done in NativeScript plugins.  It should be locked to a specific version to prevent conflicts.  Removing the geolocation plugin allows the application to be built successfully.

Here is some literature on the issue:

https://github.com/NativeScript/push-plugin/issues/101
https://github.com/EddyVerbruggen/nativescript-plugin-firebase#found-play-services900-but-version-10xy-is-needed

Please let me know when this is corrected and pushed to NPM.

Thanks

Austin Harris
Loadchief Developer

**Comment by christocracy** [comment]
I've been doing this for over 3 years with Cordova and React Native.  play-services dependency issues are very common.

Ultimately, it's your own Application which should have the final word on your desired dependencies.  It's not up to any particular plugin to dictate this.

[Read this](How to solve Google Play Services version collision in gradle dependences) and take control over your dependencies in your own `platforms/android/build.gradle`.

**Comment by nraboy** [comment]
For a paid plugin that advertises having support, I would have imagined a better response than this.

By using a '+' wildcard, it is probably the worst thing you could do and you're not doing yourself any favors because when Google changes the library and your entire plugin breaks, what are your customers going to do?  **Would be nice if you could be more specific in the supported version like '10.0.+' or something.** What should @loadchief build.gradle file look like without having to dig through a bunch of plugin source code?

Also, I'm not sure the relevancy of Apache Cordova or React Native responses in a NativeScript ticket. Are you implying that this is an unenthusiastic NativeScript port?

My two cents...

**Comment by christocracy** [comment]
I've been using :+ for about 3 years, with Cordova and React Native, long before this NativeScript port existed.  That's why I mention the other versions.

There have been no issues with Google changes "breaking everything".

**Comment by nraboy** [comment]
We're just trying to get help and offer suggestions.  We're not trying to belittle your experience.  I'm not sure why all you're so rude in all of your responses on this ticket and others that were opened.

**Comment by christocracy** [comment]
I don't think I'm being rude nor do I feel you're trying to belittle me.

I mention the "3 years" only to make it clear that this is not unusual to me to hear about play-services dependency clashes. The issue is most often related to some other 3rd party plugin pinning their plugin at a specific version.

Fortunately with NativeScript, you can take control over your own build.gradle and provide your desired version of any particular play-services dependency.

**Comment by nraboy** [comment]
If you hear about this issue so frequently, wouldn't it make sense to document this in your plugin documentation?  Document the problem as well as how to resolve it? Taking a link adventure is cool, but it is even better when it is clear in the documentation.

Would be nice to see an actual functioning build.gradle file with the changes.

**Comment by christocracy** [comment]
>If you hear about this issue so frequently, wouldn't it make sense to document this in your plugin documentation?

The problem is always with some other plugin pinning their `play-services` version.  For example, when a Cordova customer reports a similar problem, the first question I ask is "Are you using the `cordova-plugin-googlemaps` plugin?".  90% of time, it's "Yes, why?".  Over there, they're [pinning play-services at 9.8.0](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L49).

Show me the result of `$ tns plugin list`

**Comment by loadchief** [comment]
![image](https://cloud.githubusercontent.com/assets/20728482/25597678/03665ea0-2e85-11e7-80c8-3bf00e2e43dd.png)

**Comment by christocracy** [comment]
Now your next task is to determine all those plugins which include `play-services` as a dependency.

At a glance, I'd say that would be only `nativescript-push-notifications` (in addition to `nativescript-background-geolocation-lt`, which I don't see there.

**Comment by christocracy** [comment]
Obviously the `nativescript-push-notifications` people are going to be causing issues pinning their google dependencies [like they are](https://github.com/NativeScript/push-plugin/blob/master/platforms/android/include.gradle#L14)

**Comment by christocracy** [comment]
And you can see [others expressing similar conflicts](https://github.com/NativeScript/push-plugin/issues?utf8=%E2%9C%93&q=conflict) there with other plugins due to their pinned dependencies.

**Comment by loadchief** [comment]
ok, thank you Chris.  Nic and I are going to work together on Wednesday to see if we can resolve the google play conflict and get both push and tracking to work together.

**Comment by christocracy** [comment]
Clearly the problem is with `push-plugin` [pinning firebase](https://github.com/NativeScript/push-plugin/blob/master/platforms/android/include.gradle#L15) (which comes from `play-services`) at `10.0.1`.  If you were to fork their repo and modify their `build.gradle` and modify that dependency version to `:+`, or `10.:+` it will work.

And @nraboy there's no way I'd pin to `10.0.+`.  If *anything*, I'd pin to `10.2.:+`, which would still cause `push-plugin` to break the build.

The [current version of play-services](https://developers.google.com/android/guides/setup) is `10.2.4`

**Comment by loadchief** [comment]
ok, we will give that a shot, thank you!

**Comment by Daxito** [comment]
@loadchief @nraboy  Were you guys able to fix this? I am thinking about buying this plugin but I also have Push Notifications installed...

**Comment by christocracy** [comment]
@Daxito the problem is not at all with this plugin.  It's 100% an issue with the `push-plugin`.  Worst case, you fork `push-plugin` and fix their pinned `play-services` dependency.

**Comment by nraboy** [comment]
Yes, we fixed the problem @Daxito. However, it is inaccurate to say that the issue is "100% an issue with the push-plugin" as that is not the case. The problem is with Android plugins in general and having shared dependencies that require different versions. @christocracy consistently tries to deflect the issue to someone else.

We fixed the issue by forking this background-geolocation plugin and changing the versions within this plugin. We did not touch the push notification plugin as it was already locked to a specific version where as the background-geolocation plugin had a wildcard to the latest.

For now it seems to be fine, but long term I imagine there will be other issues with this approach.

Best,

**Comment by christocracy** [comment]
@nraboy When one plugin pins `play-services` as [push-plugin does](https://github.com/NativeScript/push-plugin/blob/master/platforms/android/include.gradle#L15), it is 100% the fault of the **other plugin**.  No plugin should dictate to **all other dependencies** the specific version of `play-services` we must all abide.

The best solution is to contact `push-plugin` and tell them to stop forcing all other dependences to use an out-dated play-services version `10.0.1` where the current version is `10.2.4`.

@Daxito:  @nraboy is 100% **wrong** here.

**Comment by christocracy** [comment]
>For now it seems to be fine, but long term I imagine there will be other issues with this approach.

I have 4 years experience dealing with this.  Your imagination is wrong.

**Comment by nraboy** [comment]
I've never heard of someone going into production with a wildcard version. When you do that, what you build today may not match what you build tomorrow. Pinning your dependencies is the correct thing to do.

@Daxito in all honesty, I **wouldn't** recommend buying this plugin. For a paid plugin, the support you get from @christocracy is just terrible. Look through the closed tickets if you don't believe me. It is just a NativeScript port and his responses show this due to their little love.

**Comment by christocracy** [comment]
Pinning dependencies is perfectly fine but it's your [application build.gradle's responsibility](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f) -- It's not for some 3rd party plugin to dictate to your app.

**Comment by christocracy** [comment]
Support is rapid and excellent.
