### ISSUE TITLE
The problem when scheduled location Tracking in ios

### ISSUE THREAD

**Issue by hatvott** [transistorsoft/nativescript-background-geolocation-lt#77]
Dear Chris,
we configured to automatically start and stop tracking with our calendar. But the application can't auto track the location on the next day.
We followed by your guide.
stopOnTerminate: false
startOnBoot: true;
Thank Chris so much!

**Comment by christocracy** [comment]
You must not ignore the issue template.

*****************************************************************
* WARNING:  If you ignore this template, your issue will be too.
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Nativescript version (`tns info`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
Once you provide the requested information in the **issue template**, the issue will be re-opened.
