### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by dChin84** [transistorsoft/nativescript-background-geolocation-lt#93]

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, your issue will be too.
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Nativescript version (`tns info`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
